In [ ]:
# One-Hot Encoding Example
# This notebook demonstrates how to use TensorFlow Keras' `one_hot` function to convert text sentences into one-hot encoded vectors.


In [ ]:
 tensorflow

Note: you may need to restart the kernel to use updated packages.


In [7]:
from tensorflow.keras.preprocessing.text import one_hot

In [3]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [4]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [5]:
## Define the vocabulary size
voc_size=10000

In [6]:
### One Hot Representation
one_hot_repr=[one_hot(words,voc_size)for words in sent]
one_hot_repr

[[3299, 502, 4860, 4892],
 [3299, 502, 4860, 5112],
 [3299, 9862, 4860, 9026],
 [5267, 3279, 6037, 581, 8661],
 [5267, 3279, 6037, 581, 8527],
 [4567, 3299, 63, 4860, 6787],
 [3844, 6376, 2846, 581]]

In [8]:
## word Embedding Representation
 
from tensorflow.keras.layers import Embedding
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [9]:
import numpy as np

In [10]:
sent_length=8
embedded_docs=pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 3299  502 4860 4892]
 [   0    0    0    0 3299  502 4860 5112]
 [   0    0    0    0 3299 9862 4860 9026]
 [   0    0    0 5267 3279 6037  581 8661]
 [   0    0    0 5267 3279 6037  581 8527]
 [   0    0    0 4567 3299   63 4860 6787]
 [   0    0    0    0 3844 6376 2846  581]]


In [11]:
## feature representation
dim=10

In [16]:
model=Sequential()
model.add(Embedding(voc_size, dim,input_shape=(sent_length,)))
model.compile(optimizer='adam', loss='mse')

d:\COE1\13-3-2026\.venv\Lib\site-packages\keras\src\layers\core\embedding.py:103: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


In [17]:
model.summary()

Model: "sequential_4"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_4 (Embedding)         │ (None, 8, 10)          │       100,000 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 100,000 (390.62 KB)

 Trainable params: 100,000 (390.62 KB)

 Non-trainable params: 0 (0.00 B)

In [18]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step


array([[[-4.64992635e-02,  4.85166050e-02, -3.02993301e-02,
         -1.49398558e-02, -4.41387072e-02, -1.89053901e-02,
          4.88417782e-02, -2.29931716e-02,  3.42849977e-02,
         -3.99252884e-02],
        [-4.64992635e-02,  4.85166050e-02, -3.02993301e-02,
         -1.49398558e-02, -4.41387072e-02, -1.89053901e-02,
          4.88417782e-02, -2.29931716e-02,  3.42849977e-02,
         -3.99252884e-02],
        [-4.64992635e-02,  4.85166050e-02, -3.02993301e-02,
         -1.49398558e-02, -4.41387072e-02, -1.89053901e-02,
          4.88417782e-02, -2.29931716e-02,  3.42849977e-02,
         -3.99252884e-02],
        [-4.64992635e-02,  4.85166050e-02, -3.02993301e-02,
         -1.49398558e-02, -4.41387072e-02, -1.89053901e-02,
          4.88417782e-02, -2.29931716e-02,  3.42849977e-02,
         -3.99252884e-02],
        [-2.62869522e-03, -2.99901851e-02, -1.98372491e-02,
          4.68410589e-02, -3.21351290e-02, -2.16793418e-02,
          2.64546536e-02, -1.77787058e-02, -3.434462