NLP Technique

Step 1: Lowercasing

In [2]:
text="I Love NLP"
lower_text=text.lower()
print(lower_text)

title_text=text.title()
print(title_text)

upper_text=text.upper()
print(upper_text)

i love nlp
I Love Nlp
I LOVE NLP


###step 2: Remove Punctuation
-remove symbols like . , ! ; :

In [3]:
import string
text="Wow!!! This is amazing. NLP is great,isn't it?"

#Remove punctuation
clean_text=text.translate(str.maketrans('','',string.punctuation))
print(clean_text)

Wow This is amazing NLP is greatisnt it


Step 3:Tokenization
-split text into smaller units(words or sentences)

In [4]:
from nltk.tokenize import word_tokenize
import nltk
nltk.download('punkt_tab', quiet=True)
text="Wow!!! This is amazing. NLP is great,isn't it?"
tokens=word_tokenize(text)
print(tokens)

  Using cached gensim-4.4.0.tar.gz (23.3 MB)
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
  Preparing metadata (pyproject.toml): started
  Preparing metadata (pyproject.toml): finished with status 'done'
  Using cached smart_open-7.5.1-py3-none-any.whl.metadata (24 kB)
  Using cached wrapt-2.1.2-cp314-cp314-win_amd64.whl.metadata (7.6 kB)
Using cached smart_open-7.5.1-py3-none-any.whl (64 kB)
Using cached wrapt-2.1.2-cp314-cp314-win_amd64.whl (60 kB)
Failed to build gensim


  error: subprocess-exited-with-error
  
  × Building wheel for gensim (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [716 lines of output]
      C:\Users\nakka tharun goud\AppData\Local\Temp\pip-build-env-20b41in9\overlay\Lib\site-packages\setuptools\_distutils\dist.py:287: UserWarning: Unknown distribution option: 'test_suite'
        warnings.warn(msg)
      C:\Users\nakka tharun goud\AppData\Local\Temp\pip-build-env-20b41in9\overlay\Lib\site-packages\setuptools\_distutils\dist.py:287: UserWarning: Unknown distribution option: 'tests_require'
        warnings.warn(msg)
      running bdist_wheel
      running build
      running build_py
      creating build\lib.win-amd64-cpython-314\gensim
      copying gensim\downloader.py -> build\lib.win-amd64-cpython-314\gensim
      copying gensim\interfaces.py -> build\lib.win-amd64-cpython-314\gensim
      copying gensim\matutils.py -> build\lib.win-amd64-cpython-314\gensim
      copying gensim\nosy.py -> build\lib.win-amd6

['Wow', '!', '!', '!', 'This', 'is', 'amazing', '.', 'NLP', 'is', 'great', ',', 'is', "n't", 'it', '?']


Step4: Remove the Stopwords
-remove common words that do not add the strong meaning

In [5]:
from nltk.corpus import stopwords
nltk.download('stopwords', quiet=True)
text="Wow!!! This is amazing. NLP is great,isn't it?"
tokens=word_tokenize(text)

stop_words=set(stopwords.words('english'))


In [6]:
#stemming
from nltk.stem import PorterStemmer
text="NLP is amazing. I love learning NLP."
tokens=word_tokenize(text)

stemmer=PorterStemmer()
stemmed_tokens=[stemmer.stem(token) for token in tokens]
print(stemmed_tokens)

['nlp', 'is', 'amaz', '.', 'i', 'love', 'learn', 'nlp', '.']


###Step 6: Lemmatization
- covert word to its dictionary base form

In [7]:
#lemmatization
from nltk.stem import WordNetLemmatizer
nltk.download('wordnet', quiet=True)
text="NLP is amazing. I love learning NLP."
lemmatizer=WordNetLemmatizer()
lemmatized_tokens=[lemmatizer.lemmatize(word) for word in tokens]
print(lemmatized_tokens)

['NLP', 'is', 'amazing', '.', 'I', 'love', 'learning', 'NLP', '.']


###Step 7: Remove Number
-Remove numeric value if not required

In [8]:
import re
text="Price: $100.00"
 #Remove leading/trailing whitespace
clean_text=text.strip()
print(clean_text)
#Remove number
clean_text=re.sub(r'\d+', '', clean_text)
print(clean_text)

Price: $100.00
Price: $.


Remove URL
-remove web links form text

In [9]:
import re
#link text
text="Visit our website at https://www.example.com for more info."
clean_text=re.sub(r'http\S+', '', text)
print(clean_text)

Visit our website at  for more info.


###Step 9: Remove HTML TAG
-remove html markup

In [10]:
#import lib html tag remove
import re
text="<p>This is a paragraph.</p>"
clean_text=re.sub(r'<.*?>', '', text)
print(clean_text)

This is a paragraph.


###Step 11: Bag of word
-count the frequency of each words in vocabulary

In [11]:
#import lib bag of word
from sklearn.feature_extraction.text import CountVectorizer
sentences=["I love NLP","NLP is amazing","I enjoy learning NLP"]
vectorizer=CountVectorizer()
X=vectorizer.fit_transform(sentences)
print("vocabulary:" ,vectorizer.get_feature_names_out())
print("Bag of Words Matrix:\n", X.toarray())

vocabulary: ['amazing' 'enjoy' 'is' 'learning' 'love' 'nlp']
Bag of Words Matrix:
 [[0 0 0 0 1 1]
 [1 0 1 0 0 1]
 [0 1 0 1 0 1]]


###Step 12

In [12]:
#import TF-IDF
from sklearn.feature_extraction.text import TfidfVectorizer
sentences=["I love NLP","NLP is amazing","I enjoy learning NLP"]
vectorizer=TfidfVectorizer()
X=vectorizer.fit_transform(sentences)
print("vocabulary:" ,vectorizer.get_feature_names_out())
print("TF-IDF Matrix:\n", X.toarray())

vocabulary: ['amazing' 'enjoy' 'is' 'learning' 'love' 'nlp']
TF-IDF Matrix:
 [[0.         0.         0.         0.         0.861037   0.50854232]
 [0.65249088 0.         0.65249088 0.         0.         0.38537163]
 [0.         0.65249088 0.         0.65249088 0.         0.38537163]]


###Step 13: word embedding (Word2Vec)
-each word gets dense vector like (100 or 300 dimensions)

In [13]:
!pip install gensim

  Using cached gensim-4.4.0.tar.gz (23.3 MB)
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
  Preparing metadata (pyproject.toml): started
  Preparing metadata (pyproject.toml): finished with status 'done'
  Using cached smart_open-7.5.1-py3-none-any.whl.metadata (24 kB)
  Using cached wrapt-2.1.2-cp314-cp314-win_amd64.whl.metadata (7.6 kB)
Using cached smart_open-7.5.1-py3-none-any.whl (64 kB)
Using cached wrapt-2.1.2-cp314-cp314-win_amd64.whl (60 kB)
Failed to build gensim


  error: subprocess-exited-with-error
  
  × Building wheel for gensim (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [716 lines of output]
      C:\Users\nakka tharun goud\AppData\Local\Temp\pip-build-env-uxoq0z20\overlay\Lib\site-packages\setuptools\_distutils\dist.py:287: UserWarning: Unknown distribution option: 'test_suite'
        warnings.warn(msg)
      C:\Users\nakka tharun goud\AppData\Local\Temp\pip-build-env-uxoq0z20\overlay\Lib\site-packages\setuptools\_distutils\dist.py:287: UserWarning: Unknown distribution option: 'tests_require'
        warnings.warn(msg)
      running bdist_wheel
      running build
      running build_py
      creating build\lib.win-amd64-cpython-314\gensim
      copying gensim\downloader.py -> build\lib.win-amd64-cpython-314\gensim
      copying gensim\interfaces.py -> build\lib.win-amd64-cpython-314\gensim
      copying gensim\matutils.py -> build\lib.win-amd64-cpython-314\gensim
      copying gensim\nosy.py -> build\lib.win-amd6

In [14]:
sentences=[["I","love","NLP"],["NLP","is","amazing"],["I","enjoy","learning","NLP"]]
model=Word2Vec(sentences, vector_size=100, window=5, min_count=1, workers=4)
print(model.wv['NLP'])

NameError: name 'Word2Vec' is not defined

In [ ]:
from transformer import AutoTokenizer, AutoModel
import torch
tokenizer=AutoTokenizer.from_pretrained('bert-base-uncased')
model=AutoModel.from_pretrained('bert-base-uncased')
text="I love NLP"
input=tokenizer(text, return_tensors='pt')
output=model(**input)
print(output.last_hidden_state.shape)

In [ ]:
# saved the embeddings
torch.save(output.last_hidden_state, "bert_embeddings.pt")\
 